# Generated by Django 4.2 on 2025-11-19 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
